### ISSUE TITLE
More operators from APL

### ISSUE THREAD

**Issue by ghost** [ZippyMagician/Arn#2]
* Arguments swapping
* Argument copying
* Logarithm / Natural logarithm (`⍟`)
* Take (`↑`)
* Drop (`↓`)

**Comment by ZippyMagician** [comment]
What do you mean by swapping and copying? The others will most likely show up in some form

**Comment by ghost** [comment]
@ZippyMagician By operand swapping, I mean a function that takes another function, and modifies the function such that the operands of this function are taken in reverse.

Argument copying is basically a modifier of an infix function to make it prefix or postfix. And then, when you apply a value to the function, the value will be copied to the other side of the infix function.

These exact things are done in the `⍨` operator.

**Comment by ghost** [comment]
Other suggestions:

* `×` (signum)
* `÷` (reciprocal)
* `|` (Absolute value)
* Vectorization (APL does it implicitly; you probably want to do this as well)

**Comment by ZippyMagician** [comment]
Vectorization is implicit when necessary. The copying suggestions sounds like a good idea too. I’m not so sure about the use cases of the operand swapping.

**Comment by ZippyMagician** [comment]
List for you:

1.  Argument swapping: **probably not**
2. Argument copying: **yes**
3. Logarithms: **yes** (eventually). Currently `bignumber.js` does not support logarithms, I have left an issue.
4. Take: **Implemented as `.{`**
5. Drop: **Implemented as `.}`**
6. Signum: **maybe**
7. Reciprocal: **can't, you can do `1/` already so it would have to be a 1-character fix, all of which are taken**
8. Absolute value: **Implemented as `.|`**
