### ISSUE TITLE
Small website design suggestion

### ISSUE THREAD

**Issue by razetime** [ZippyMagician/Arn#3]
It would be nice to have the output above the SE markdown generator. Would make it simpler to check output instead of scrolling.

**Comment by ZippyMagician** [comment]
Thanks for the feedback. I'll compare the two and see which is nicer

**Comment by ZippyMagician** [comment]
After testing a few different possibilities, I picked the one I liked the most; there is now a button in the header to toggle the visibility of the SE Post Template. Thanks for pointing this out, I use a large monitor so I would have never noticed this.
