### ISSUE TITLE
`[1 1 {+}]` doesn't works

### ISSUE THREAD

**Issue by RustemB** [ZippyMagician/Arn#4]
instead it prints
```
1
1
0
0
0
0
...
```

**Comment by ZippyMagician** [comment]
I just ran it, and it worked. Are you using the latest version, and could you run `rustc -vV` and send what it outputs?

**Comment by RustemB** [comment]
i use git version of arn
```
$ rustc -vV
rustc 1.54.0-nightly (9111b8ae9 2021-05-26)
binary: rustc
commit-hash: 9111b8ae9793f18179a1336417618fc07a9cac85
commit-date: 2021-05-26
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.1
```

**Comment by ZippyMagician** [comment]
Hmm, could you send the contents of the file you are running? It’s possible there’s something goin on with compression. I’m going to try rebuilding it on nightly and seeing if that breaks anything, but I highly doubt it...

**Comment by RustemB** [comment]
```
[1 1 {+}]
```

```
$ hexdump -C fibs.arn
00000000  5b 31 20 31 20 7b 2b 7d  5d 0a                    |[1 1 {+}].|
0000000a
```

**Comment by ZippyMagician** [comment]
Is it possible to remove the trailing newline and then rerunning? It’s been an issue in the past for some reason

**Comment by RustemB** [comment]
i don't have this newline in my text editor

**Comment by RustemB** [comment]
but even when i remove this new line it doesn't work

**Comment by ZippyMagician** [comment]
Okay I just ran it in nightly and it breaks. It seems like something changes from 1.52 to 1.54 that causes the code to change how it functions. Until I solve this, just rebuild the project with `cargo +stable install —path path/to/repo`

**Comment by RustemB** [comment]
nah, not work even on stable

**Comment by RustemB** [comment]
```
$ strings ./path/to/arn | rg 'rustc version'
clang LLVM (rustc version 1.52.1 (9bc8c42bb 2021-05-09))
```

**Comment by ZippyMagician** [comment]
This has been fixed. It was an issue with `utils::traverse_replace` not applying to the block, resulting in every new value being the input doubled instead (in this case, `0`). See 0808a99
